pipeline {
    agent any

    parameters {
        choice(
            name: 'ACTION',
            choices: ['apply', 'destroy'],
            description: 'Terraform action'
        )
    }

    environment {
        AWS_REGION         = "ap-south-1"
        AWS_DEFAULT_REGION = "ap-south-1"
        TF_DIR             = "terraformProject/main"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/durveshyadav3604/cloud-projects.git',
                    credentialsId: 'github-token'
            }
        }

        stage('Terraform Init') {
            steps {
                withCredentials([[ 
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-terraform-creds'
                ]]) {
                    dir("${TF_DIR}") {
                        sh '''
                          echo "🔐 Verifying AWS identity..."
                          aws sts get-caller-identity

                          echo "🚀 Initializing Terraform..."
                          rm -rf .terraform
                          terraform init -reconfigure
                        '''
                    }
                }
            }
        }

        stage('Terraform Plan') {
            when {
                expression { params.ACTION == 'apply' }
            }
            steps {
                withCredentials([[ 
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-terraform-creds'
                ]]) {
                    dir("${TF_DIR}") {
                        sh 'terraform plan -out=tfplan'
                    }
                }
            }
        }

        stage('Terraform Apply / Destroy') {
           steps {
               withCredentials([[ 
                   $class: 'AmazonWebServicesCredentialsBinding',
                   credentialsId: 'aws-terraform-creds'
               ]]) {
                   dir("${TF_DIR}") {
                       script {
                           if (params.ACTION == 'apply') {
                               sh 'terraform apply -auto-approve'
                           } else {
                               sh 'terraform destroy -auto-approve'
                           }
                       } // close script
                   } // close dir
               } // close withCredentials
           } // close steps
       } // close stage
    } // close stages

    post {
        success {
            echo "✅ Terraform ${params.ACTION} completed successfully"
        }
        failure {
            echo "❌ Terraform ${params.ACTION} failed"
        }
    }
}

